### ISSUE TITLE
не рабочая ссылка

### ISSUE THREAD

**Issue by boomsya** [pavel-drobushevich/blog#1]
добрый день
нашел ваш блог ну и пытался найти хоть какой-то контакт с вами

интересен вот этот пост
http://pdrobushevich.blogspot.com/2010/04/java-decompiler.html

увы ссылка на Java Decompiler не работает
не могли бы вы поделиться свежей ссылкой?

буду очень благодарен

**Comment by pavel-drabushevich** [comment]
Добрый день,

К сожалению не могу. Так как им не пользовался очень давно. Последние 5 лет java была только для развлечения и поэтому не нужно было разбираться в закрытых исходниках. А вот когда несколько месяцев назад вернулся к java обнаружил что моя любимая Jetbrains IDEA прекрасно с этой задачей справляется из коробки https://blog.jetbrains.com/idea/2014/07/intellij-idea-14-eap-138-1029-is-out/ Так что могу посоветовать просто ей пользоваться если есть возможность.

**Comment by boomsya** [comment]
программа шикарна, я их ПО пользуюсь давно
просто там в примере используется JAR файл
а APK лежит DEX файл

у меня есть комплект программ для декомпиляции. Просто есть некоторые случаи, когда оно создает переменные $assertionsDisabled и функцию desiredAssertionStatus

но всё равно спасибо за ответ
